
retail.sources = dir
retail.channels = buffer
retail.sinks = kafka

retail.sources.dir.type = spooldir
retail.sources.dir.spoolDir = /var/log/flume_lab/retailpulse
retail.sources.dir.batchSize = 500
retail.sources.dir.channels = buffer

retail.sources.dir.ignorePattern = ^.*\.tmp$
retail.sources.dir.fileSuffix = .COMPLETED
retail.sources.dir.deletePolicy = never
retail.sources.dir.deserializer = LINE
retail.sources.dir.deserializer.maxLineLength = 8192
retail.sources.dir.inputCharset = UTF-8

retail.sources.dir.basenameHeader = true
retail.sources.dir.basenameHeaderKey = source_file

# ---------- Interceptor ----------
retail.sources.dir.interceptors = i_key

retail.sources.dir.interceptors.i_key.type = regex_extractor
retail.sources.dir.interceptors.i_key.regex = "session_id"\s*:\s*"([^"]+)"
retail.sources.dir.interceptors.i_key.serializers = s1
retail.sources.dir.interceptors.i_key.serializers.s1.name = key

# ---------- Channel: durable File channel ----------
#retail.channels.ch_events.type = file
#retail.channels.ch_events.checkpointDir = /var/lib/flume/_state/checkpoint
#retail.channels.ch_events.dataDirs = /var/lib/flume/_state/data
#retail.channels.ch_events.capacity = 1000000
#retail.channels.ch_events.transactionCapacity = 1000

retail.channels.buffer.type = file
retail.channels.buffer.checkpointDir = /var/lib/flume/retail/checkpoint
retail.channels.buffer.dataDirs = /var/lib/flume/retail/data
retail.channels.buffer.capacity = 10000
retail.channels.buffer.transactionCapacity = 500


# ---------- Sink: Kafka ----------
retail.sinks.kafka.type = org.apache.flume.sink.kafka.KafkaSink
retail.sinks.kafka.channel = buffer
retail.sinks.kafka.kafka.bootstrap.servers = kafka:9092
retail.sinks.kafka.kafka.topic = retailpulse
retail.sinks.kafka.flumeBatchSize = 500
retail.sinks.kafka.kafka.producer.acks = all
retail.sinks.kafka.kafka.producer.compression.type = snappy
retail.sinks.kafka.kafka.producer.linger.ms = 20
retail.sinks.kafka.useFlumeEventFormat = false
